# @file .markdownlint.yml
#
# markdownlint configuration file
#
##
# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: Apache-2.0
##
{
    "default": true,
    "MD013": {"line_length": 120, "code_blocks": false, "tables": false},
    "MD033": {"allowed_elements": ["br", "center", "div"]}
}
